import 'package:flutter/material.dart';
import 'package:my_nba/models/team_model.dart';
import 'package:my_nba/data/database_helper.dart';

class TeamPage extends StatefulWidget {
  @override
  _TeamPageState createState() => _TeamPageState();
}

class _TeamPageState extends State<TeamPage> {
  final TextEditingController _cityController = TextEditingController();
  final TextEditingController _homeCourtController = TextEditingController();
  final TextEditingController _divisionController = TextEditingController();

  late DatabaseHelper _databaseHelper;

  @override
  void initState() {
    super.initState();
    _databaseHelper = DatabaseHelper();
  }
  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Teams Page'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TextField(
              controller: _cityController,
              decoration: const InputDecoration(labelText: 'City'),
            ),
            TextField(
              controller: _homeCourtController,
              decoration: const InputDecoration(labelText: 'Home Court'),
            ),
            TextField(
              controller: _divisionController,
              decoration: const InputDecoration(labelText: 'Division'),
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                ElevatedButton(
                  onPressed: () {
                    _insertTeam();
                  },
                  child: const Text('Create Team'),
                ),
                const SizedBox(width: 16),
                ElevatedButton(
                  onPressed: () {
                    _updateTeam();
                  },
                  child: const Text('Update Team'),
                ),
                const SizedBox(width: 16),
                ElevatedButton(
                  onPressed: () {
                    _deleteTeam();
                  },
                  child: const Text('Delete Team'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  void _insertTeam() async {
    String city = _cityController.text.trim();
    String homeCourt = _homeCourtController.text.trim();
    String division = _divisionController.text.trim();

    Team newTeam = Team(
      teamID: '', // Set to empty, as it will be auto-generated by the database
      city: city,
      homeCourt: homeCourt,
      division: division,
    );

    String teamId = (await _databaseHelper.insertTeam(newTeam)) as String;
    print('Team inserted with ID: $teamId');
  }

  void _updateTeam() async {
    // Assuming you have the team ID from somewhere (e.g., selected team)
    String teamIdToUpdate = 'Rockets'; // Replace with the actual team ID

    String city = _cityController.text.trim();
    String homeCourt = _homeCourtController.text.trim();
    String division = _divisionController.text.trim();

    Team updatedTeam = Team(
      teamID: teamIdToUpdate,
      city: city,
      homeCourt: homeCourt,
      division: division,
    );

    int rowsAffected = await _databaseHelper.updateTeam(updatedTeam);
    print('Updated $rowsAffected team(s)');
  }

  void _deleteTeam() async {
    // Assuming you have the team ID from somewhere (e.g., selected team)
    String teamIdToDelete = 'Rockets'; // Replace with the actual team ID

    int rowsDeleted = await _databaseHelper.deleteTeam(teamIdToDelete);
    print('Deleted $rowsDeleted team(s)');
  }
}
